Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.bucket}
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: AddTransitionAndExpiration
            Status: Enabled
            ExpirationInDays: 1095
            Transitions:
              - TransitionInDays: 183
                StorageClass: DEEP_ARCHIVE
      ReplicationConfiguration:
        Role: !GetAtt BucketReplicationRole.Arn
        Rules:
          - Id: ReplicateToBackup1
            Status: Enabled
            Filter:
              Prefix: ''
            Priority: 1
            DeleteMarkerReplication:
              Status: Enabled
            Destination:
              Bucket: 'arn:aws:s3:::${self:custom.bucketBackup1}'
              ReplicationTime:
                Status: Enabled
                Time:
                  Minutes: 15
              Metrics:
                Status: Enabled
                EventThreshold:
                  Minutes: 15

  BucketReplicationRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: ${self:custom.bucket}-bucket-replication-role
      Path: "/"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ${self:custom.bucket}-bucket-replication-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:GetReplicationConfiguration'
                  - 's3:ListBucket'
                  - 's3:GetObjectVersionForReplication'
                  - 's3:GetObjectVersionAcl'
                  - 's3:GetObjectVersionTagging'
                  - 's3:GetObjectAcl'
                Resource:
                  - 'arn:aws:s3:::${self:custom.bucket}'
                  - 'arn:aws:s3:::${self:custom.bucket}/*'
              - Effect: Allow
                Action:
                  - 's3:ReplicateObject'
                  - 's3:ReplicateDelete'
                  - 's3:ReplicateTags'
                Resource:
                  - 'arn:aws:s3:::${self:custom.bucketBackup1}'
                  - 'arn:aws:s3:::${self:custom.bucketBackup1}/*'
